script: phpunit

# travis configuration
language: php
php:
    - 5.3
# variables d'envirronement
env:
    - ODM_MONGODB_TEST_CONNECTION_STRING=localhost ODM_MONGODB_TEST_DATABASE_NAME=tests

# install les packages avec composer
before_script:
    - composer install
    - chmod +xwr tests
    - phpenv config-add php.travis.ini

# executer phpunit
script: phpunit

services: mongodb

